### ISSUE TITLE
 xevuan/usr/share/xevuan/backuphome 

### ISSUE THREAD

**Issue by z-empyrean** [dessington/xevuan#2]
for tmux users, maybe use awk as such otherwise it picks up two of the same user in the script and fails?
line 3
https://github.com/dessington/xevuan/blob/master/usr/share/xevuan/backuphome

`_user="$(who|awk 'NR==1 {print $1}')"`

or maybe use logname

`_user="$(logname)"`

**Comment by dessington** [comment]
Thanks for the tip, I will test it with the new scripts and integrate, ideally it should be as compatible as possible.

This is the last update of Xevuan (excepting major bugs) as DXT2 was discontinued and is currently being replaced with a Void base. This will eventually replace both DXT2 & Xevuan. An alpha image will be available in the coming weeks.

**Comment by dessington** [comment]
Thank you also for testing ;)
